# -*- coding: utf-8 -*-
"""Degrau_Unitário.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18EKxw2bdPuQaCT6dql-5pTVnRErRwXTg
"""

#Importando bibliotecas
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp

#Parâmetros do sistema
m1 = 6.0       #Massa não suspensa [kg]
m2 = 58.5      #Massa suspensa [kg]
k1 = 39500.0   #Rigidez do pneu [N/m]
k2 = 3950.0    #Rigidez da mola da suspensão [N/m]

#Coeficientes de amortecimento para diferentes valores de zeta
zeta = [0.7, 1.0, 1.4]
b = [2 * z * np.sqrt(k2 * m2) for z in zeta]

#Configuração da simulação temporal
t_span = (0, 2) #Tempo inicial e final [s]
t_eval = np.arange(0, 2.001, 0.001) #Vetor temporal com passo de 1ms

#Função de entrada degrau unitário
def u(t):
    return 1.0 if t >= 0 else 0.0

#Sistema dinâmico de ¼ de suspensão
def sistema(t, Y, m1, m2, b, k1, k2):
    x, dx, y, dy = Y  # Descompacta os estados

    #Equações diferenciais do sistema
    ddx = (-b * (dx - dy) - k2 * (x - y) - k1 * (x - u(t))) / m1
    ddy = (-b * (dy - dx) - k2 * (y - x)) / m2

    return [dx, ddx, dy, ddy]

#Simulação para cada valor de amortecimento
for i, bi in enumerate(b):
    #Resolve o sistema de EDOs
    sol = solve_ivp(sistema, t_span, [0, 0, 0, 0],
                    args=(m1, m2, bi, k1, k2),
                    t_eval=t_eval,
                    method='RK45')

    #Extrai os resultados
    x = sol.y[0]  #Posição da massa não suspensa
    y = sol.y[2]  #Posição da massa suspensa

    #Plot dos resultados
    plt.figure(figsize=(10, 4))
    plt.plot(t_eval, x, label='x(t) - Massa não suspensa')
    plt.plot(t_eval, y, '--', label='y(t) - Massa suspensa')

    plt.title(f'Resposta do Sistema para ζ = {zeta[i]}')
    plt.xlabel('Tempo [s]')
    plt.ylabel('Amplitude')
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.show()